# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ea7820fe0a34dd3cb0e8db36fef283e6a3680534b4d2e6293fc6b219b0672ec6a9d72e35a9d88c43762a7b22e5e215d24f70c5de7b03c014fe9c5879ddc047d

  sorcery_facebook_callback_url: "http://0.0.0.0:3000/oauth/callback?provider=facebook"
  sorcery_facebook_key: <%= ENV["1781873105445779"] %>
  sorcery_facebook_secret: <%= ENV["ed5412dc5b246a8a9d831124a74cb4e9"] %>

  sorcery_twitter_callback_url: "http://0.0.0.0:3000/oauth/callback?provider=twitter"
  twitter_consumer_key: <%= ENV["cOMwUlZjM6n4a8DhaieQyhqmf"] %>
  twitter_consumer_secret: <%= ENV["Ez21a2bqEHpExk3JvI16dHj2Sy24Ogp7ob3SnvJpa3C1jdejeL"] %>


test:
  secret_key_base: 5c69ad2639296fd079c134488647c76ffec8fb42c271f7cd3a65e4464c7442e8b3469c79dd92957c89b58f38c598a59e4a811dbb3bd871552d2615da4d320a03

  sorcery_facebook_callback_url: "http://0.0.0.0:3000/oauth/callback?provider=facebook"
  sorcery_facebook_key: <%= ENV["1781873105445779"] %>
  sorcery_facebook_secret: <%= ENV["ed5412dc5b246a8a9d831124a74cb4e9"] %>

  sorcery_twitter_callback_url: "http://0.0.0.0:3000/oauth/callback?provider=twitter"
  sorcery_twitter_key: <%= ENV["cOMwUlZjM6n4a8DhaieQyhqmf"] %>
  sorcery_twitter_secret: <%= ENV["Ez21a2bqEHpExk3JvI16dHj2Sy24Ogp7ob3SnvJpa3C1jdejeL"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  sorcery_facebook_callback_url: "http://0.0.0.0:3000/oauth/callback?provider=facebook"
  sorcery_facebook_key: <%= ENV["1781873105445779"] %>
  sorcery_facebook_secret: <%= ENV["ed5412dc5b246a8a9d831124a74cb4e9"] %>

  sorcery_twitter_callback_url: "http://0.0.0.0:3000/oauth/callback?provider=twitter"
  sorcery_twitter_key: <%= ENV["cOMwUlZjM6n4a8DhaieQyhqmf"] %>
  sorcery_twitter_secret: <%= ENV["Ez21a2bqEHpExk3JvI16dHj2Sy24Ogp7ob3SnvJpa3C1jdejeL"] %>